/** Representative exam-technique packages for 8 topics. Seeded into exam_question_patterns; not mass lesson generation. */

export const EXAM_TECHNIQUE_EXAMPLES = [
  {
    topic: "Paragrafta Yapı — cümle sıralama",
    master_key_name: "Paragrafta Yapı",
    subject: "Türkçe",
    minimum_theory: "Giriş cümlesi genelde önceki bağlama ihtiyaç duymaz. 'bu, ancak, çünkü, dolayısıyla' çoğu zaman önceki bilgiye bağlanır.",
    recognition_trigger: "Soru hangi cümlenin başa / ikinci sıraya / önce-sonraya geleceğini sorar.",
    first_move: "Cümle başlarındaki bağlaç ve göndermeleri tara; bağlama bağımlı adayları ele.",
    fast_strategy: "Bağımsız giriş adayı seç, sonra anlamla doğrula. Tüm metni iki kez okumak ilk hamle değil.",
    common_traps: "Akılda kalan ayrıntılı cümleyi giriş sanmak; bağlacı kesin kural gibi kullanmak.",
    when_not_to_use: "Bağımsız görünen iki aday kalırsa anlam bütünlüğü olmadan seçme.",
    heuristic_kind: "strong_clue",
    fast_rule: "Bağlaçla başlayan cümle çoğu zaman giriş değildir. Önce bağımsız başlayanı ara, sonra anlamla doğrula.",
    memory_hook: "Kapı tokmağı: bağlaç = 'önce biri konuşmuş'.",
    checkpoint: "Giriş cümlesi arıyorsun. İlk kontrol?",
  },
  {
    topic: "Yüzde problemleri",
    master_key_name: "Problemler",
    subject: "Matematik",
    minimum_theory: "%20 artış ×1,20; %20 azalış ×0,80. Aynı oran artış-azalış başlangıca dönmez.",
    recognition_trigger: "Kökte yüzde, zam, indirim, kâr, oran artışı geçer.",
    first_move: "Başlangıcı 100 al veya çarpan yaz. Şıkları ancak modelden hızlıysa dene.",
    fast_strategy: "100 → 120 → 96. Şıktan gitme: orta değeri dene, uçları ele.",
    common_traps: "Zam ve indirimin birbirini götürdüğünü sanmak.",
    when_not_to_use: "Bileşik yüzde basamakları belirsizse veya birim değişiyorsa çarpanı körlemesine uygulama.",
    heuristic_kind: "rule",
    fast_rule: "Zam ve indirim aynı oran olsa bile başlangıca dönmez.",
    memory_hook: "100 altın → 120 → 96: taç küçüldü.",
    checkpoint: "Yüzde artış-azalış görünce ilk ne yazarsın?",
  },
  {
    topic: "Kut / Töre / Kurultay",
    master_key_name: "İslamiyet Öncesi Türk Tarihi",
    subject: "Tarih",
    minimum_theory: "Kut: tanrısal yönetme yetkisi. Töre: hukuk-gelenek. Kurultay: devlet meclisi.",
    recognition_trigger: "Kökte kutsal meşruiyet, hanedan, taht kavgaları, töre, kurultay geçer.",
    first_move: "Anahtar kelimeyi kavrama bağla; karıştırılan çifti kontrastla.",
    fast_strategy: "Kut zinciri: kutsal yetki → hanedan üyeleri → veraset belirsizliği → taht kavgaları.",
    common_traps: "Kut ile Töre'yi, Kurultay ile Divan'ı eşitlemek.",
    when_not_to_use: "Soru Osmanlı divan teşkilatını soruyorsa Göktürk kurultayına çekme.",
    heuristic_kind: "mnemonic",
    fast_rule: "Kut = tanrısal yetki. Töre = kural. Kurultay = meclis.",
    memory_hook: "Altın taç = Kut.",
    checkpoint: "'İlahi yönetme yetkisi' deyince ilk hangi kavram?",
  },
  {
    topic: "Dağların kıyıya paralel uzanması",
    master_key_name: "Yer Şekilleri",
    subject: "Coğrafya",
    minimum_theory: "Kıyıya paralel dağlar: kıyı-iç ulaşımı zor, nem içeri az sızar, bölgesel zıtlık artar.",
    recognition_trigger: "Harita veya kökte dağ uzanış yönü, kıyı-iç farkı, iklim geçişi sorulur.",
    first_move: "Haritada bölge, yön, yükselti, kıyı doğrultusunu oku; metni sonra doğrula.",
    fast_strategy: "Uzanış → ulaşım/iklim/bölgesel zıtlık zincirini hatırla.",
    common_traps: "Enine uzanışı boyuna gibi okumak; tek cümlelik tanımı sonuç sanmak.",
    when_not_to_use: "Dağlar kıyıya dikse nem içeri sokulur; paralel kuralını tersine çevir.",
    heuristic_kind: "strong_clue",
    fast_rule: "Kıyıya paralel dağ görünce: ulaşım zor, iklim içeri zor girer, zıtlık artar.",
    memory_hook: "Duvar gibi dağ: deniz içeri giremez.",
    checkpoint: "Haritada kıyıya paralel dağ görünce ilk sonuç?",
  },
  {
    topic: "Kurum-yetki eşlemesi",
    master_key_name: "Yargı",
    subject: "Vatandaşlık",
    minimum_theory: "TBMM kanun. Anayasa Mahkemesi anayasa denetimi. İdari yargı idari uyuşmazlık.",
    recognition_trigger: "Hangi kurumun hangi işlemi yaptığı / hangisinin bakamayacağı sorulur.",
    first_move: "Kurum → yetki → işlem türü ızgarasını aç.",
    fast_strategy: "Önce işlem türünü (kanun/yönetmelik/yargı) belirle, sonra kurumu eşle.",
    common_traps: "Yargı organlarını yürütme ile karıştırmak; eski anayasa kuralını güncel sanmak.",
    when_not_to_use: "Soru tarihî 1924/1961 düzenini soruyorsa 1982 ızgarasını yapıştırma.",
    heuristic_kind: "rule",
    fast_rule: "Önce işlem türü, sonra kurum. Kanun = TBMM, anayasa denetimi = AYM.",
    memory_hook: "Üç kapı: yasama / yürütme / yargı.",
    checkpoint: "Anayasa aykırılığı iddiasında ilk hangi kapı?",
  },
  {
    topic: "Hareket grafik yorumu",
    master_key_name: "Hareket",
    subject: "Fizik",
    minimum_theory: "x-t eğim = hız. v-t alan = yer değiştirme, eğim = ivme.",
    recognition_trigger: "Grafikte eksenler konum-zaman veya hız-zaman; eğim/alan sorulur.",
    first_move: "Eksenleri oku. Uzun hikâyeden önce grafiğe bak.",
    fast_strategy: "Eksen eşlemesi → eğim mi alan mı? Sonra işaret/yön.",
    common_traps: "x-t grafiğinde eğimi ivme sanmak; alanı hız sanmak.",
    when_not_to_use: "Eksenler ivme-zaman ise x-t kurallarını taşıma.",
    heuristic_kind: "rule",
    fast_rule: "Önce eksen. x-t eğim=hız. v-t alan=yer değiştirme, eğim=ivme.",
    memory_hook: "Merdiven eğimi = hız; boyanan alan = yol.",
    checkpoint: "Grafik sorusunda ilk neye bakarsın?",
  },
  {
    topic: "Periyodik eğilimler",
    master_key_name: "Atom ve Periyodik Sistem",
    subject: "Kimya",
    minimum_theory: "Sağa ve yukarı: elektronegatiflik ve iyonlaşma enerjisi genelde artar; atom yarıçapı sola ve aşağı artar. İstisnalar ayrı.",
    recognition_trigger: "Hangi elementin yarıçapı/iyonlaşma/elektronegatifliği daha büyük sorulur.",
    first_move: "Periyodik yön haritasını çiz; istisna listesini kontrol et.",
    fast_strategy: "Konum → genel eğilim → istisna var mı.",
    common_traps: "Eğilimi istisnasız kural sanmak (Be/B, N/O gibi).",
    when_not_to_use: "Geçiş metalleri veya yarı dolu/orbital istisnası varken ezber oku kullanma.",
    heuristic_kind: "strong_clue",
    fast_rule: "Yarıçap sola-aşağı büyür. Elektronegatiflik sağa-yukarı artar. İstisnayı ayrı kontrol et.",
    memory_hook: "Oklar: yarıçap şişer sola-aşağı, elektron sevgisi sağa-yukarı.",
    checkpoint: "İyonlaşma enerjisi karşılaştırmasında ilk adım?",
  },
  {
    topic: "Organel işlev anahtarları",
    master_key_name: "Hücre Organelleri",
    subject: "Biyoloji",
    minimum_theory: "Ribozom=protein. Mitokondri=ATP. Golgi=paketleme. Lizozom=hücre içi sindirim.",
    recognition_trigger: "İşlev, organel veya 'hangisi ... yapar' kökü.",
    first_move: "İşlev anahtar kelimesini organele bağla, sonra uygulama şıkkını ele.",
    fast_strategy: "Anahtar → organel → şıkta işlev sapmasını ele.",
    common_traps: "Golgi ile ER'yi, mitokondri ile kloroplastı karıştırmak.",
    when_not_to_use: "Soru bitki özgü plastidleri soruyorsa hayvan hücresi kartını yapıştırma.",
    heuristic_kind: "mnemonic",
    fast_rule: "Ribozom protein, mitokondri ATP, Golgi kargo, lizozom çöp öğütücü.",
    memory_hook: "Fabrika: tezgahtar ribozom, enerji santrali mitokondri.",
    checkpoint: "'ATP üretir' deyince ilk organel?",
  },
] as const;
